/**
 * OpenAPI 3.0 document for the Forth Urban API, served via swagger-ui-express
 * at `/api/docs` (see docs/DEPLOYMENT.md and app.ts for the mounting rule:
 * open in non-production, gated behind `requireAuth + requireRole("admin")`
 * in production — Phase 10 exit criterion in
 * docs/IMPLEMENTATION_PLAN.md#phase-10--cicd--deployment).
 *
 * Scope decision: this document is hand-maintained here (not generated by
 * scanning per-route JSDoc comments with swagger-jsdoc) to keep ~65 endpoints
 * across 22 route files in one reviewable place. Request/response bodies use
 * a generic `Envelope` wrapper + `object` payload schemas rather than full
 * per-DTO field definitions — the Zod schemas in packages/validation remain
 * the single source of truth for exact shapes; this spec is for discovering
 * "what endpoints exist, what do they need, do they require auth" rather
 * than full client-code generation. Extend individual `paths` entries with
 * richer schemas over time as needed.
 */

const envelope = (dataSchema: Record<string, unknown> = { type: "object", nullable: true }) => ({
  type: "object",
  properties: {
    success: { type: "boolean" },
    message: { type: "string" },
    data: dataSchema,
    errors: { type: "array", nullable: true, items: {} },
  },
});

const jsonResponse = (description: string, dataSchema?: Record<string, unknown>) => ({
  description,
  content: { "application/json": { schema: envelope(dataSchema) } },
});

const okResponses = (description = "Success") => ({
  200: jsonResponse(description),
});

const createdResponses = (description = "Created") => ({
  201: jsonResponse(description),
  400: jsonResponse("Validation error"),
});

const authErrorResponses = {
  401: jsonResponse("Missing/invalid access token"),
};

const adminErrorResponses = {
  401: jsonResponse("Missing/invalid access token"),
  403: jsonResponse("Authenticated but not an admin"),
};

const bearerAuth = [{ bearerAuth: [] }];

type Operation = Record<string, unknown>;

function op(
  summary: string,
  tags: string[],
  opts: {
    auth?: "none" | "user" | "admin";
    body?: boolean;
    params?: Array<{ name: string; description?: string }>;
    responses?: Record<number, unknown>;
    successStatus?: 200 | 201;
  } = {},
): Operation {
  const { auth = "user", body = false, params = [], successStatus = 200 } = opts;
  const responses: Record<string, unknown> = {
    ...(successStatus === 201 ? createdResponses() : okResponses()),
  };
  if (auth === "user") Object.assign(responses, authErrorResponses);
  if (auth === "admin") Object.assign(responses, adminErrorResponses);
  if (opts.responses) Object.assign(responses, opts.responses);

  const result: Operation = {
    summary,
    tags,
    responses,
  };
  if (auth !== "none") result.security = bearerAuth;
  if (body) {
    result.requestBody = {
      required: true,
      content: { "application/json": { schema: { type: "object" } } },
    };
  }
  if (params.length > 0) {
    result.parameters = params.map((p) => ({
      name: p.name,
      in: "path",
      required: true,
      description: p.description,
      schema: { type: "string" },
    }));
  }
  return result;
}

export const openApiDocument = {
  openapi: "3.0.3",
  info: {
    title: "Forth Urban AI Property Advisor API",
    version: "0.1.0",
    description:
      "Account-gated real estate consultation funnel API for Abuja land sales. " +
      "See docs/ARCHITECTURE.md for the Decision Engine vs LLM Advisory Layer split.",
  },
  servers: [{ description: "Current environment", url: "/api" }],
  tags: [
    { name: "Health" },
    { name: "Auth" },
    { name: "Users" },
    { name: "Profiles" },
    { name: "Quiz" },
    { name: "Properties" },
    { name: "Recommendations" },
    { name: "Calculators" },
    { name: "AI Advisory" },
    { name: "Inspections" },
    { name: "Notifications" },
    { name: "Events" },
    { name: "Admin" },
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
        description: "Short-lived access token returned by /auth/login, /auth/register, /auth/otp/verify, /auth/refresh.",
      },
    },
  },
  paths: {
    "/health": { get: op("Liveness check", ["Health"], { auth: "none" }) },

    "/auth/register": { post: op("Register with email + password", ["Auth"], { auth: "none", body: true, successStatus: 201 }) },
    "/auth/login": { post: op("Log in with email + password", ["Auth"], { auth: "none", body: true }) },
    "/auth/otp/request": { post: op("Request an email OTP code", ["Auth"], { auth: "none", body: true }) },
    "/auth/otp/verify": { post: op("Verify an email OTP code and log in", ["Auth"], { auth: "none", body: true }) },
    "/auth/refresh": {
      post: op("Exchange the refresh cookie for a new access token (requires CSRF header)", ["Auth"], { auth: "none" }),
    },
    "/auth/logout": {
      post: op("Revoke the current session (requires CSRF header)", ["Auth"], { auth: "none" }),
    },
    "/auth/password/forgot": { post: op("Request a password reset email", ["Auth"], { auth: "none", body: true }) },
    "/auth/password/reset": { post: op("Reset password with a reset token", ["Auth"], { auth: "none", body: true }) },
    "/auth/google": { get: op("Start Google OAuth login (redirect)", ["Auth"], { auth: "none" }) },
    "/auth/google/callback": { get: op("Google OAuth callback (redirect)", ["Auth"], { auth: "none" }) },
    "/auth/me": { get: op("Get the current authenticated user", ["Auth"]) },

    "/users/me": {
      get: op("Get the current user's account record", ["Users"]),
      patch: op("Update the current user's account record", ["Users"], { body: true }),
    },

    "/profiles/me": { get: op("Get the current user's buyer profile", ["Profiles"]) },

    "/quiz/home-readiness/start": { post: op("Mark the Home-Readiness Quiz as started", ["Quiz"]) },
    "/quiz/home-readiness": { post: op("Submit Home-Readiness Quiz answers", ["Quiz"], { body: true, successStatus: 201 }) },
    "/quiz/home-readiness/result": { get: op("Get the latest Home-Readiness Quiz result", ["Quiz"]) },
    "/quiz/area/start": { post: op("Mark the Best Abuja Area Quiz as started", ["Quiz"]) },
    "/quiz/area": { post: op("Submit Best Abuja Area Quiz answers", ["Quiz"], { body: true, successStatus: 201 }) },
    "/quiz/area/result": { get: op("Get the latest Best Abuja Area Quiz result", ["Quiz"]) },

    "/properties": { get: op("List active properties", ["Properties"]) },
    "/properties/{id}": {
      get: op("Get a property's detail", ["Properties"], { params: [{ name: "id" }], responses: { 404: jsonResponse("Not found") } }),
    },

    "/recommendations/properties": {
      get: op("Get properties matched to the current user's profile", ["Recommendations"]),
    },

    "/calculators/budget": { post: op("Run the Budget/Affordability calculator", ["Calculators"], { body: true, successStatus: 201 }) },
    "/calculators/hidden-cost": {
      post: op("Run the Hidden Cost calculator", ["Calculators"], { body: true, successStatus: 201 }),
    },
    "/calculators/roi": { post: op("Run the ROI calculator", ["Calculators"], { body: true, successStatus: 201 }) },

    "/ai/quiz-summary": {
      post: op("LLM explanation of a Home-Readiness Quiz result", ["AI Advisory"], { successStatus: 201 }),
    },
    "/ai/buyer-persona": {
      post: op("LLM explanation of the assigned buyer persona", ["AI Advisory"], { successStatus: 201 }),
    },
    "/ai/recommendation-explainer": {
      post: op("LLM explanation of why a property was recommended", ["AI Advisory"], { body: true, successStatus: 201 }),
    },
    "/ai/roi-explainer": {
      post: op("LLM explanation of an ROI calculator result", ["AI Advisory"], { body: true, successStatus: 201 }),
    },
    "/ai/inspection-advice": {
      post: op("LLM inspection-day guidance", ["AI Advisory"], { body: true, successStatus: 201 }),
    },
    "/ai/ask": {
      post: op("Free-form follow-up question to the AI advisor", ["AI Advisory"], { body: true, successStatus: 201 }),
    },

    "/inspections": { post: op("Book a land inspection", ["Inspections"], { body: true, successStatus: 201 }) },
    "/inspections/me": { get: op("List the current user's inspection bookings", ["Inspections"]) },

    "/notifications/me": { get: op("List the current user's notifications", ["Notifications"]) },
    "/notifications/{id}/read": {
      patch: op("Mark a notification as read", ["Notifications"], { params: [{ name: "id" }] }),
    },

    "/events": { post: op("Track a client-fired analytics event", ["Events"], { body: true, successStatus: 201 }) },

    "/admin/users": { get: op("List users", ["Admin"], { auth: "admin" }) },
    "/admin/users/{id}": {
      get: op("Get a user", ["Admin"], { auth: "admin", params: [{ name: "id" }] }),
      patch: op("Update a user (e.g. role)", ["Admin"], { auth: "admin", body: true, params: [{ name: "id" }] }),
    },
    "/admin/properties": {
      get: op("List properties (admin)", ["Admin"], { auth: "admin" }),
      post: op("Create a property", ["Admin"], { auth: "admin", body: true, successStatus: 201 }),
    },
    "/admin/properties/{id}": {
      get: op("Get a property (admin)", ["Admin"], { auth: "admin", params: [{ name: "id" }] }),
      patch: op("Update a property", ["Admin"], { auth: "admin", body: true, params: [{ name: "id" }] }),
      delete: op("Soft-delete a property", ["Admin"], { auth: "admin", params: [{ name: "id" }] }),
    },
    "/admin/properties/{id}/media": {
      post: op("Upload property media to Cloudinary", ["Admin"], {
        auth: "admin",
        body: true,
        params: [{ name: "id" }],
        successStatus: 201,
      }),
      delete: op("Remove a property media item (deletes from Cloudinary too)", ["Admin"], {
        auth: "admin",
        body: true,
        params: [{ name: "id" }],
      }),
    },
    "/admin/inspections": { get: op("List inspection bookings", ["Admin"], { auth: "admin" }) },
    "/admin/inspections/{id}": {
      patch: op("Update an inspection booking's status", ["Admin"], { auth: "admin", body: true, params: [{ name: "id" }] }),
    },
    "/admin/crm": { get: op("List CRM lead events", ["Admin"], { auth: "admin" }) },
    "/admin/crm/{userId}": {
      patch: op("Append a new CRM pipeline-stage event for a user", ["Admin"], {
        auth: "admin",
        body: true,
        params: [{ name: "userId" }],
        successStatus: 201,
      }),
    },
    "/admin/email-campaigns": { get: op("List aggregated email campaign stats", ["Admin"], { auth: "admin" }) },
    "/admin/analytics/quiz": { get: op("Quiz funnel + readiness/lead-category analytics", ["Admin"], { auth: "admin" }) },
    "/admin/logs": { get: op("Paginated audit log", ["Admin"], { auth: "admin" }) },
    "/admin/settings": {
      get: op("Get ROI defaults / property-match weights", ["Admin"], { auth: "admin" }),
      patch: op("Update ROI defaults / property-match weights", ["Admin"], { auth: "admin", body: true }),
    },
    "/admin/areas": {
      get: op("List area preference->name mappings", ["Admin"], { auth: "admin" }),
      post: op("Add an area mapping", ["Admin"], { auth: "admin", body: true, successStatus: 201 }),
    },
    "/admin/areas/{id}": {
      delete: op("Remove an area mapping", ["Admin"], { auth: "admin", params: [{ name: "id" }] }),
    },
    "/admin/prompts": { get: op("List AI prompt files", ["Admin"], { auth: "admin" }) },
    "/admin/prompts/{key}": {
      get: op("Get one AI prompt file", ["Admin"], { auth: "admin", params: [{ name: "key" }] }),
      patch: op("Save a new version of an AI prompt file", ["Admin"], {
        auth: "admin",
        body: true,
        params: [{ name: "key" }],
      }),
    },
    "/admin/prompts/{key}/preview": {
      post: op("Preview an AI prompt against sample context", ["Admin"], {
        auth: "admin",
        body: true,
        params: [{ name: "key" }],
        successStatus: 201,
      }),
    },
  },
};
