import { Schema, model, type HydratedDocument, type InferSchemaType } from "mongoose";
import { applyBaseSchema } from "../../db/base-schema.plugin.js";

/**
 * `recommendations` collection — see docs/ARCHITECTURE.md#5-database-schema-mongodb-atlas.
 *
 * Persists which properties were shown to which user and why, generated by
 * the Decision Engine's property matching (property-matching.ts) each time
 * `GET /api/recommendations/properties` is called. One document per
 * (userId, propertyId) pair — upserted so a re-match refreshes the score and
 * reasonTags instead of accumulating duplicates.
 */
const recommendationSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
  propertyId: { type: Schema.Types.ObjectId, ref: "Property", required: true, index: true },
  reasonTags: { type: [String], required: true, default: [] },
  score: { type: Number, required: true, min: 0 },
  source: { type: String, enum: ["quiz", "areaQuiz", "manual"], required: true },
});

recommendationSchema.index({ userId: 1, propertyId: 1 }, { unique: true });

applyBaseSchema(recommendationSchema);

export type RecommendationDocument = HydratedDocument<InferSchemaType<typeof recommendationSchema>>;

export const Recommendation = model("Recommendation", recommendationSchema);
